# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e23f9760bca814d67172ed611a6c047d"
name = "product-level-discount"
handle = "product-level-discount-1"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "discountfunctionsofmaha.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2025-01"

[pos]
embedded = false
